version: '3.6'
services:
  app:
    container_name: membership_service
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    env_file: ./.env
    volumes:
      - api:/usr/src/app/
    depends_on:
      - mysql

  mysql:
    image: mysql
    build: ./db/docker
    container_name: mysql_db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${ENV_DB_NAME}
      - MYSQL_USER=${ENV_DB_USER}
      - MYSQL_PASSWORD=${ENV_DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${ENV_DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql 
      
volumes:
  api:
  mysql_data: